// factory-weekly-report (Phase 04 Step 9). One issue per week: merged factory tickets, blocked
// tickets, attempts used, Actions minutes (sum of run wall-clock, an approximation; billing APIs
// need an admin/user token), Copilot premium-request use if the API allows it with this token
// (otherwise UNKNOWN), Cursor and Bugbot cost UNKNOWN (no API wired).
// Env: GH_TOKEN (github.token, issues: write), GITHUB_REPOSITORY, AMIT, DRY_RUN=1.
import { gh, ghAll, repoParts, summary } from "./gh-api.mjs";
import { labelNames } from "./factory-lib.mjs";

const { owner, repo } = repoParts();
const since = new Date(Date.now() - 7 * 864e5);
const day = since.toISOString().slice(0, 10);
const q = (s) => gh(`/search/issues?q=${encodeURIComponent(s)}&per_page=100`);
const merged = (await q(`repo:${owner}/${repo} is:pr is:merged label:factory merged:>=${day}`)).items;
const blocked = (await q(`repo:${owner}/${repo} is:open label:blocked:amit`)).items;
const attempts = { "attempt:1": 0, "attempt:2": 0, "attempt:3": 0, "mergefix:1": 0, "mergefix:2": 0 };
for (const pr of (await q(`repo:${owner}/${repo} is:pr label:factory updated:>=${day}`)).items) for (const l of labelNames(pr)) if (l in attempts) attempts[l]++;
const runs = await ghAll(`/repos/${owner}/${repo}/actions/runs?created=>=${day}`, (j) => j.workflow_runs, 3000);
const minutes = Math.round(runs.reduce((s, r) => s + Math.max(0, new Date(r.updated_at) - new Date(r.run_started_at || r.created_at)), 0) / 60000);
let copilot = "UNKNOWN (the premium-request usage API needs a user/admin token; not available to github.token)";
try { const u = await gh(`/users/${process.env.AMIT || "Division6066"}/settings/billing/premium_request/usage`); copilot = "```json\n" + JSON.stringify(u).slice(0, 1500) + "\n```"; } catch { /* stays UNKNOWN */ }
const body = [
  `Week from ${day} (UTC). Generated by factory-weekly-report.`,
  `## Merged factory tickets (${merged.length})`, ...merged.map((p) => `- #${p.number} ${p.title}`),
  `## Blocked (blocked:amit, open: ${blocked.length})`, ...blocked.map((i) => `- #${i.number} ${i.title}`),
  `## Attempts used (factory PRs updated this week)`, ...Object.entries(attempts).map(([k, v]) => `- ${k}: ${v}`),
  `## Actions minutes`, `- ~${minutes} min wall-clock across ${runs.length} runs (approximation; billed minutes need the billing API).`,
  `## Copilot premium requests`, copilot,
  `## Cursor and Bugbot cost`, `UNKNOWN (no API wired).`,
].join("\n");
if (process.env.DRY_RUN === "1") { console.log(body); process.exit(0); }
const issue = await gh(`/repos/${owner}/${repo}/issues`, { method: "POST", body: { title: `Factory weekly report ${day}`, body, assignees: [process.env.AMIT || "Division6066"] } });
await summary([`Weekly report: ${issue.html_url}`]);
