import { Router, type IRouter } from "express";
import healthRouter from "./health";
import tasksRouter from "./tasks";
import notesRouter from "./notes";
import projectsRouter from "./projects";
import foldersRouter from "./folders";
import tagsRouter from "./tags";
import dailyPlansRouter from "./dailyPlans";
import preferencesRouter from "./preferences";
import memoriesRouter from "./memories";
import templatesRouter from "./templates";
import aiRouter from "./ai";
import stagingRouter from "./staging";
import calendarEventsRouter from "./calendarEvents";
import noteLinksRouter from "./noteLinks";
import savedFiltersRouter from "./savedFilters";
import noteTemplatesRouter from "./noteTemplates";
import searchRouter from "./search";
import transcribeRouter from "./transcribe";
import authRouter from "./auth";
import importRouter from "./import";
import exportRouter from "./export";
import accountRouter from "./account";
import attachmentsRouter from "./attachments";
import voiceRouter from "./voice";
import libStatusRouter from "./libStatus";
import ttsRouter from "./tts";

const router: IRouter = Router();

router.use(authRouter);
router.use(healthRouter);
router.use(tasksRouter);
router.use(notesRouter);
router.use(projectsRouter);
router.use(foldersRouter);
router.use(tagsRouter);
router.use(dailyPlansRouter);
router.use(preferencesRouter);
router.use(memoriesRouter);
router.use(templatesRouter);
router.use(aiRouter);
router.use(stagingRouter);
router.use(calendarEventsRouter);
router.use(noteLinksRouter);
router.use(savedFiltersRouter);
router.use(noteTemplatesRouter);
router.use(searchRouter);
router.use(transcribeRouter);
router.use(importRouter);
router.use(exportRouter);
router.use(accountRouter);
router.use(attachmentsRouter);
router.use(voiceRouter);
router.use(libStatusRouter);
router.use(ttsRouter);

export default router;
