import { MOCK_USER_ID } from "./config";
import { DAY_MS, startOfLocalDay } from "./windows";
import type { CalendarEvent, Goal, Habit, Memory, Task, TaskRepeatCfg, TempoSnapshot } from "./types";

function atHour(dayOffset: number, hour: number, minute = 0, now = Date.now()): number {
  const d = new Date(startOfLocalDay(now));
  d.setDate(d.getDate() + dayOffset);
  d.setHours(hour, minute, 0, 0);
  return d.getTime();
}

function id(prefix: string, n: number): string {
  return `${prefix}_${n}`;
}

export function buildSeed(now = Date.now()): TempoSnapshot {
  const userId = MOCK_USER_ID;
  const today = startOfLocalDay(now);

  const tasks: Task[] = [
    {
      _id: id("task", 1),
      userId,
      title: "Email the lecturer about the extension",
      description: "Opened the draft five times. Still in Drafts.",
      status: "todo",
      priority: "high",
      energy: "medium",
      timeEstimate: 15 * 60 * 1000,
      projectId: "school",
      projectName: "Mechina",
      dueAt: atHour(-4, 11, 0, now),
      createdAt: today - 12 * DAY_MS,
      updatedAt: atHour(-1, 9, 0, now),
      avoidCount: 5,
      lastAvoidedAt: atHour(-1, 9, 0, now),
    },
    {
      _id: id("task", 2),
      userId,
      title: "Sort the paperwork pile",
      description: "The one on the desk. Ten minutes, then stop.",
      status: "todo",
      priority: "low",
      energy: "low",
      dueAt: atHour(-2, 16, 0, now),
      createdAt: today - 8 * DAY_MS,
      updatedAt: atHour(-2, 16, 0, now),
      avoidCount: 2,
      lastAvoidedAt: atHour(-2, 16, 0, now),
    },
    {
      _id: id("task", 3),
      userId,
      title: "Physio stretches, 20 minutes",
      description: "Lying down, TENS on. Do not sit for this.",
      status: "todo",
      priority: "high",
      energy: "low",
      timeEstimate: 20 * 60 * 1000,
      projectId: "body",
      projectName: "Rehab",
      dueAt: atHour(0, 9, 30, now),
      createdAt: today - 3 * DAY_MS,
      updatedAt: today - 3 * DAY_MS,
      avoidCount: 0,
      checklist: [
        { id: "c1", text: "Lay the mat out", completed: false },
        { id: "c2", text: "Ten hip openers", completed: false },
        { id: "c3", text: "Ice if it spikes", completed: false },
      ],
    },
    {
      _id: id("task", 4),
      userId,
      title: "Take morning meds",
      status: "todo",
      priority: "high",
      energy: "low",
      dueAt: atHour(0, 8, 0, now),
      createdAt: today - 20 * DAY_MS,
      updatedAt: today - DAY_MS,
      repeatCfgId: id("repeat", 1),
    },
    {
      _id: id("task", 5),
      userId,
      title: "Read 8 pages of the physics chapter",
      description: "Stop at page 8 even if it is going well.",
      status: "todo",
      priority: "medium",
      energy: "medium",
      timeEstimate: 40 * 60 * 1000,
      projectId: "school",
      projectName: "Mechina",
      dueAt: atHour(0, 14, 0, now),
      createdAt: today - 2 * DAY_MS,
      updatedAt: today - 2 * DAY_MS,
    },
    {
      _id: id("task", 6),
      userId,
      title: "Write the lab report draft",
      description: "Full draft. This is a high-energy block.",
      status: "todo",
      priority: "high",
      energy: "high",
      timeEstimate: 90 * 60 * 1000,
      projectId: "school",
      projectName: "Mechina",
      dueAt: atHour(0, 16, 0, now),
      createdAt: today - 5 * DAY_MS,
      updatedAt: today - 5 * DAY_MS,
    },
    {
      _id: id("task", 7),
      userId,
      title: "Practice driving theory flashcards",
      status: "in_progress",
      priority: "medium",
      energy: "low",
      dueAt: atHour(0, 19, 0, now),
      createdAt: today - 6 * DAY_MS,
      updatedAt: atHour(0, 7, 0, now),
      projectId: "life",
      projectName: "Driving",
    },
    {
      _id: id("task", 8),
      userId,
      title: "Text back about Saturday",
      status: "todo",
      priority: "low",
      energy: "low",
      dueAt: atHour(1, 12, 0, now),
      createdAt: today - DAY_MS,
      updatedAt: today - DAY_MS,
    },
    {
      _id: id("task", 9),
      userId,
      title: "Book the practical driving test",
      description: "You said this month. The calendar is open Tuesday.",
      status: "todo",
      priority: "high",
      energy: "medium",
      dueAt: atHour(-1, 13, 0, now),
      createdAt: today - 18 * DAY_MS,
      updatedAt: atHour(-1, 13, 0, now),
      avoidCount: 3,
      lastAvoidedAt: atHour(-1, 13, 0, now),
      projectId: "life",
      projectName: "Driving",
    },
    {
      _id: id("task", 10),
      userId,
      title: "Review yesterday's notes",
      status: "done",
      priority: "medium",
      energy: "low",
      dueAt: atHour(-1, 10, 0, now),
      createdAt: today - 4 * DAY_MS,
      updatedAt: atHour(-1, 10, 20, now),
    },
    {
      _id: id("task", 11),
      userId,
      title: "Fill the weekly pill box",
      status: "done",
      priority: "medium",
      energy: "low",
      dueAt: atHour(-3, 18, 0, now),
      createdAt: today - 10 * DAY_MS,
      updatedAt: atHour(-3, 18, 10, now),
    },
    {
      _id: id("task", 12),
      userId,
      title: "Twenty-minute walk",
      status: "done",
      priority: "low",
      energy: "low",
      dueAt: atHour(-2, 17, 0, now),
      createdAt: today - 7 * DAY_MS,
      updatedAt: atHour(-2, 17, 30, now),
    },
    {
      _id: id("task", 13),
      userId,
      title: "Math problem set, first three only",
      status: "done",
      priority: "medium",
      energy: "medium",
      dueAt: atHour(-4, 15, 0, now),
      createdAt: today - 9 * DAY_MS,
      updatedAt: atHour(-4, 16, 0, now),
    },
    {
      _id: id("task", 14),
      userId,
      title: "Call home",
      status: "done",
      priority: "low",
      energy: "low",
      dueAt: atHour(-5, 20, 0, now),
      createdAt: today - 12 * DAY_MS,
      updatedAt: atHour(-5, 20, 15, now),
    },
    {
      _id: id("task", 15),
      userId,
      title: "Karate — light class",
      status: "done",
      priority: "medium",
      energy: "medium",
      dueAt: atHour(-6, 19, 0, now),
      createdAt: today - 14 * DAY_MS,
      updatedAt: atHour(-6, 21, 0, now),
    },
  ];

  const memories: Memory[] = [
    {
      _id: id("mem", 1),
      userId,
      content: "You said you would book the practical driving test this month.",
      sector: "episodic",
      salience: 0.92,
      decayRate: 0.05,
      lastAccessed: atHour(-1, 13, 0, now),
      accessCount: 6,
      metadata: { kind: "commitment", relatedTaskId: id("task", 9) },
      createdAt: today - 18 * DAY_MS,
      updatedAt: atHour(-1, 13, 0, now),
    },
    {
      _id: id("mem", 2),
      userId,
      content: "The lecturer email has been opened and closed five times. It is not a writing problem.",
      sector: "emotional",
      salience: 0.88,
      decayRate: 0.08,
      lastAccessed: atHour(-1, 9, 0, now),
      accessCount: 8,
      metadata: { kind: "avoidance", relatedTaskId: id("task", 1) },
      createdAt: today - 12 * DAY_MS,
      updatedAt: atHour(-1, 9, 0, now),
    },
    {
      _id: id("mem", 3),
      userId,
      content: "Physio works better lying down with the TENS, not sitting at the desk.",
      sector: "procedural",
      salience: 0.74,
      decayRate: 0.04,
      lastAccessed: atHour(-3, 9, 0, now),
      accessCount: 4,
      metadata: { kind: "fact", relatedTaskId: id("task", 3) },
      createdAt: today - 40 * DAY_MS,
      updatedAt: atHour(-3, 9, 0, now),
    },
    {
      _id: id("mem", 4),
      userId,
      content: "Karate is the only place that reliably resets the day.",
      sector: "emotional",
      salience: 0.81,
      decayRate: 0.06,
      lastAccessed: atHour(-6, 21, 0, now),
      accessCount: 11,
      metadata: { kind: "fact" },
      createdAt: today - 90 * DAY_MS,
      updatedAt: atHour(-6, 21, 0, now),
    },
    {
      _id: id("mem", 5),
      userId,
      content: "Energy crashes after about 90 minutes of focused work. Stop before the crash.",
      sector: "semantic",
      salience: 0.79,
      decayRate: 0.03,
      lastAccessed: atHour(-2, 15, 0, now),
      accessCount: 9,
      metadata: { kind: "fact" },
      createdAt: today - 60 * DAY_MS,
      updatedAt: atHour(-2, 15, 0, now),
    },
    {
      _id: id("mem", 6),
      userId,
      content: "You told yourself the paperwork pile was a ten-minute job. It has sat for two days.",
      sector: "episodic",
      salience: 0.61,
      decayRate: 0.1,
      lastAccessed: atHour(-2, 16, 0, now),
      accessCount: 3,
      metadata: { kind: "avoidance", relatedTaskId: id("task", 2) },
      createdAt: today - 8 * DAY_MS,
      updatedAt: atHour(-2, 16, 0, now),
    },
  ];

  const habits: Habit[] = [
    {
      _id: id("habit", 1),
      userId,
      name: "Morning meds",
      cadence: "daily",
      currentStreak: 11,
      longestStreak: 18,
      lastCompletedAt: atHour(-1, 8, 5, now),
      createdAt: today - 80 * DAY_MS,
      updatedAt: atHour(-1, 8, 5, now),
    },
    {
      _id: id("habit", 2),
      userId,
      name: "Evening wind-down",
      cadence: "daily",
      currentStreak: 3,
      longestStreak: 9,
      lastCompletedAt: atHour(-1, 22, 0, now),
      createdAt: today - 40 * DAY_MS,
      updatedAt: atHour(-1, 22, 0, now),
    },
    {
      _id: id("habit", 3),
      userId,
      name: "Walk around the block",
      cadence: "daily",
      currentStreak: 0,
      longestStreak: 7,
      lastCompletedAt: atHour(-5, 17, 0, now),
      createdAt: today - 30 * DAY_MS,
      updatedAt: atHour(-5, 17, 0, now),
    },
  ];

  const goals: Goal[] = [
    {
      _id: id("goal", 1),
      userId,
      title: "Sit the practical driving test",
      description: "Booked is progress. Passed is later.",
      targetDate: atHour(40, 10, 0, now),
      progressPercent: 42,
      status: "active",
      createdAt: today - 50 * DAY_MS,
      updatedAt: atHour(-1, 13, 0, now),
    },
    {
      _id: id("goal", 2),
      userId,
      title: "Finish the mechina math module",
      progressPercent: 18,
      status: "active",
      createdAt: today - 20 * DAY_MS,
      updatedAt: atHour(-4, 16, 0, now),
    },
  ];

  const events: CalendarEvent[] = [
    {
      _id: id("event", 1),
      userId,
      title: "Physio window",
      startsAtMs: atHour(0, 9, 30, now),
      createdAt: today - 3 * DAY_MS,
      updatedAt: today - 3 * DAY_MS,
    },
    {
      _id: id("event", 2),
      userId,
      title: "Study block",
      startsAtMs: atHour(0, 14, 0, now),
      createdAt: today - 2 * DAY_MS,
      updatedAt: today - 2 * DAY_MS,
    },
  ];

  const repeatCfgs: TaskRepeatCfg[] = [
    {
      _id: id("repeat", 1),
      userId,
      repeatCycle: "DAILY",
      repeatEvery: 1,
      weekdays: [0, 1, 2, 3, 4, 5, 6],
      deletedInstanceDates: [],
      skipOverdue: true,
      waitForCompletion: false,
      repeatFromCompletionDate: false,
      isPaused: false,
      createdAt: today - 20 * DAY_MS,
      updatedAt: today - 20 * DAY_MS,
    },
  ];

  return {
    userId,
    tasks,
    memories,
    habits,
    goals,
    events,
    repeatCfgs,
    dismissedNudgeIds: [],
    demo: "seeded",
  };
}

export function emptySnapshot(): TempoSnapshot {
  return {
    userId: MOCK_USER_ID,
    tasks: [],
    memories: [],
    habits: [],
    goals: [],
    events: [],
    repeatCfgs: [],
    dismissedNudgeIds: [],
    demo: "empty",
  };
}
